# Notice: Do not update to add or delete elements from Array and List.
#         The update causes malfunction.

logging:
  config: config/log4j2-light.xml
  level:
    kr.co.uplus.agent.snap: info

agent:
#  name: snap
#  id: normal-01
  origin:
    kisa-origin-code: # Required: value should be enclosed in single quotes ('')
    rcs:
      agency-id:
      agency-key:
      brand-key:
  queue:
    type: memory
    file-queue:
      queue-prefix: snap
      queue-path: queue
      item-size: 4096
      allow-overflow-yn: n
      encryption-yn: n
  send-time: # Required: value should be enclosed in single quotes ('')
    - day-of-week: '0'
      start-time: '1000'
      end-time: '1000'
  same-phone-delay-second: 3
  duplicate-check-second: 600
  shutdown-timeout-second: 60
  password-encryption:
    use-yn: n # y (connection.info-list.pwd, spring.database.hikari.password should be encrypted value.)
    seed:
  content-file-path:
    mms:
    mms-mo:
    msghub-mo:
    download:

connection:
  info-list: # remove unused connection.info-list elements, before start-up
    - vendor: lgu
      schema: sms
      line-type: normal
      host: localhost
      port: 11000
      id: SM000000
      pwd: password
      ratio: 1
    - vendor: lgu
      schema: mms
      line-type: normal
      host: localhost
      port: 8100
      id: SM000000
      pwd: password
      ratio: 1
    - vendor: msghub
      schema: ums
      line-type: normal
      host: https://api.msghub.uplus.co.kr
      port: 443
      id: API000HUB1
      pwd: password
      tps: 50
      ratio: 1
    - vendor: msghub
      schema: kv
      line-type: normal
      host: https://api.msghub.uplus.co.kr
      port: 443
      id: API000HUB2
      pwd: password
      tps: 50
      ratio: 1

database:
  mapper-path: config/mapper
  type: oracle # oracle, mssql, mysql (even when using maraidb), postgres
  customize: lgu
  code-map:
    mapping-channel-list:

spring:
  datasource:
    hikari:
# mssql
#      jdbc-url: jdbc:log4jdbc:sqlserver://localhost:1433;databaseName=snap_db;encrypt=true;trustServerCertificate=true
#      username: snap_mssql
#      password: 1234
# mysql/mariadb
#      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/snap_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
#      username: snap_maria
#      password: 1234
# oracle
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      username: snap_oracle
      password: 1234
# tibero
#      jdbc-url: jdbc:log4jdbc:tibero:thin:@localhost:8629:tibero
#      username: snap_tibero
#      password: 1234
# postgres
#      jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
#      username: snap_postgres
#      password: 1234

watchdog:
  use-yn: n # y
  check-interval-second: 30
  logging-term-second: 1
  alarm:
    use-yn: n # y
    callback: '1234-1234' # Required: value should be enclosed in single quotes ('')
    phones: # Required: value should be enclosed in single quotes ('')
      - '01012341234'
      - '01011112222'

table:
  use-yn:
    auto-creation: y
  log-type: month # unuse, one, month
  name:
    sms:
      send: SC_TRAN
      log: SC_LOG
      mo: MO_TRAN
    mms:
      send: MMS_MSG
      log: MMS_LOG
      mo: MMS_MO
    rcs:
      send: RCS_MSG
      log: RCS_LOG
      image: RCS_IMG
    msghub:
      image: MSGHUB_IMG
      mo: MSGHUB_MO
    ums:
      send: UMS_MSG
      log: UMS_LOG
    kv:
      send: KV_MSG
      log: KV_LOG
